In [2]:
import pandas as pd

In [ ]:
data = {
    "Name": ["Rahul", "Aman", "Neha"],
    "Age": [22, 24, 21],
    "marks":[85,56,45],
    "City": ["Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  marks    City
0  Rahul   22     85   Delhi
1   Aman   24     56  Mumbai
2   Neha   21     45    Pune

In [7]:
df.to_csv("student1.csv",index=False)

In [10]:
df=pd.read_csv("student.csv",sep=";")
df

                Name  Age,marks,City
0  Rahul,22,85,Delhi             NaN
1  Aman,24,56,Mumbai             NaN
2    Neha,21,45,Pune             NaN

In [12]:
df=pd.read_csv("student.csv",header=None)
df

       0    1      2       3
0   Name  Age  marks    City
1  Rahul   22     85   Delhi
2   Aman   24     56  Mumbai
3   Neha   21     45    Pune

In [15]:
pd.read_csv("student.csv", usecols=["Name", "marks"])

    Name  marks
0  Rahul     85
1   Aman     56
2   Neha     45

In [18]:
pd.read_csv("student.csv", na_values=["NA", "null", "-"])

    Name   Age marks   City
0  Rahul  22.0    85  Delhi
1   Aman   NaN  none    NaN
2    NaN  21.0    45   Pune